server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Servir archivos estáticos — simula Azure CDN + Blob Storage
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de assets estáticos (CSS, JS, imágenes)
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1h;
        add_header Cache-Control "public";
    }

    # Logs accesibles en Docker
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;
}
